### ISSUE TITLE
Can't use search() if you want to find "zankyou no teror"

### ISSUE THREAD

**Issue by LittleEndu** [Utagai/spice#17]
C:\Users\Endrik\Google Drive\Python\MAL scraper>python getids.py "['darker than black','zankyou no teror','hellsing','berserk','death note','code geass','monster']"

Found id for 'darker than black': 2025. MAL title: 'Darker than Black: Kuro no Keiyakusha'

Traceback (most recent call last):
  File "getids.py", line 16, in <module>
    results = spice.search(i,spice.get_medium("anime"), creds)
  File "C:\Users\Endrik\AppData\Local\Programs\Python\Python35-32\lib\site-packages\spice_api\spice.py", line 169, in search
    return helpers.reschedule(search, constants.DEFAULT_WAIT, query, medium)
  File "C:\Users\Endrik\AppData\Local\Programs\Python\Python35-32\lib\site-packages\spice_api\helpers.py", line 106, in reschedule
    return func(*args)
TypeError: search() missing 1 required positional argument: 'credentials'

Found id for 'hellsing': 270. MAL title: 'Hellsing'
Found id for 'berserk': 33. MAL title: 'Berserk'
Found id for 'death note': 1535. MAL title: 'Death Note'
Found id for 'code geass': 1575. MAL title: 'Code Geass: Hangyaku no Lelouch'
Found id for 'monster': 19. MAL title: 'Monster'
['2025', '270', '33', '1535', '1575', '19']

As you see the code finds one ID then says it has no credentials but then continues to use these credentials to find 5 more anime IDs

**Comment by Utagai** [comment]
I actually think I know the problem here. I'll see if I can get a bit of time this coming weekend to fix this quickly and push a new version of the package onto PyPI, along with some other merge additions contributed (very generously) by some other users.

**Comment by Nekmo** [comment]
This problem has already been solved. https://github.com/Utagai/spice/pull/10/commits/717a2cc24ad969e1caec2aabeffc30a796c6ec91

Please use the latest version at Github.

```
pip install git+https://github.com/Utagai/spice.git@master#egg=spice_api
```

**Comment by Utagai** [comment]
Yay~.

**Comment by Utagai** [comment]
PyPi has been updated. You can use `pip --upgrade` now.
