### ISSUE TITLE
BeautifulSoup error when trying to fetch user's list of animes

### ISSUE THREAD

**Issue by nickdex** [Utagai/spice#27]
getting this error when using get_list()
```
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by nickdex** [comment]
Solved by running `pip install lxml`

**Comment by eshrh** [comment]
This has been recognized in #20 and #22, and it has since been solved by #19 which for some reason was lost and then again by #23! We only need a new version pushed now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickdex** [comment]
alright 😄

**Comment by Utagai** [comment]
Yeah, I will have to update this on pypi. Sorry about the inconvenience @nickdex, thankfully the solution is quite trivial, but it is nonetheless something that should not exist.

**Comment by nickdex** [comment]
no worries there's one more bug regarding to_json() methon in anime object. I'll try to submit PR soon
