### ISSUE TITLE
Is it medium_list instead of anime/manga_list ?

### ISSUE THREAD

**Issue by chin8628** [Utagai/spice#29]
According to README, I have to call `mlist.anime/manga_list`  for getting an anime or manga list but I cannot do it. I have to use `mlist.medium_list` instead. 

I got `AttributeError` when I called `anime/manga_list`.

This is intentional or just forgot to update README?
Sorry, If this is my wrong.

**Comment by Utagai** [comment]
Hey, what are you executing exactly? If you're running `get_medium("anime/manga_list")` that won't work. You'll have to run:

1) `get_medium("anime")` for anime.
2) `get_medium("manga")` for manga.

Note the lack of any slashes. Just a string of the type and nothing else.

**Comment by chin8628** [comment]
I want to get an anime list of a specified user. I tried to call the anime_list on List object, but it doesn't work. Could you explain more about anime and manga list attribute of List object?

**Comment by eshanmind** [comment]
to get the anime list of a specified user, you just need to run:
+for anime:
`spice_api.get_list(spice.get_medium('anime'), 'usernameOfTheUser', yourCredentials)`
+for manga:
`spice_api.get_list(spice.get_medium('manga'), 'usernameOfTheUser', yourCredentials)`

**Comment by Utagai** [comment]
Sure. If I understand you correctly, you want to get the anime list of a specified user. You can do this as long as you have the target user's username. Here's an example:

We will grab my own anime list. This uses my MAL account.
```
# Make sure you have a properly instantiated creds tuple:
>>> creds = spice_api.init_auth("YOUR_USERNAME", "YOUR_PASSWORD")
# You can also load the credentials from a file
>>> my_list = spice_api.get_list(spice_api.get_medium('anime'), 'utagai-', creds)
>>> my_list.avg_score()
5.658634538152611
```

Here is some example output from the REPL, for myself:

```
>>> for anime in my_list.medium_list['watching']:
...     print(anime.title)
...
Bleach
Ginga Eiyuu Densetsu
Darker than Black: Kuro no Keiyakusha
Toaru Majutsu no Index
Toaru Kagaku no Railgun
Tales of Zestiria the X
Sakamoto desu ga?
Planetarian: Chiisana Hoshi no Yume
Quanzhi Gaoshou
Grancrest Senki
Boruto: Naruto Next Generations
Black Clover (TV)
Mahoutsukai no Yome
3-gatsu no Lion 2nd Season
Darling in the FranXX
>>>
```

**Comment by eshrh** [comment]
Yeah, that's an error in the readme, the Readme says to use `Medium_List.anime/manga_list`, when you really need to use `Medium_List.medium_list`

**Comment by chin8628** [comment]
It works now. Thank you for the explanation.
And yes, I got confused because of an error in the readme.

Sorry for my grammatical error, English isn't my main language.

**Comment by Utagai** [comment]
No worries! The README still needs some work so I'll be creating an issue referencing this one.
